### ISSUE TITLE
The bot doesn't allow new users send polls after completing captcha. 

### ISSUE THREAD

**Issue by meltedeel** [DeMaximilianster/MF-Bot#79]
Just add `can_send_polls=True`, will you? 
https://github.com/DeMaximilianster/MF-Bot/blob/c6a91a7daaf4362761bb3f53fd9a03ba79f19253/presenter/logic/complicated_commands.py#L42-L47

**Comment by DeMaximilianster** [comment]
Alright, will do. May I ask you though? Do we know each other? It's very unusual somebody created an issue in my repo

**Comment by DeMaximilianster** [comment]
Fixed
